#!/bin/bash

echo
echo '                .__       .__               .__   '
echo '          _____ |__| ____ |__| _____ _____  |  |  '
echo '         /     \|  |/    \|  |/     \\__  \ |  |  '
echo '        |  Y Y  \  |   |  \  |  Y Y  \/ __ \|  |__'
echo '        |__|_|  /__|___|  /__|__|_|  (____  /____/'
echo '              \/        \/         \/     \/      '
echo '                               _____.__           '
echo '            ____  ____   _____/ ____\__| ____     '
echo '          _/ ___\/  _ \ /    \   __\|  |/ ___\    '
echo '          \  \__(  <_> )   |  \  |  |  / /_/  >   '
echo '           \___  >____/|___|  /__|  |__\___  /    '
echo '               \/           \/        /_____/     '
echo

githubLoad() {
    path="$1"
    dest="$2"
    wget -q --no-check-certificate -O "$dest" "https://raw.githubusercontent.com/$path"
}

rootpath="sharkdp/config-files/master/minimal-config"
files=".vimrc .bashrc .alias .profile"

bd="$HOME/.backup-config-files"
rm -rf "${bd}"
mkdir "${bd}"

for file in $files; do
    path="$HOME/$file"
    if [[ -e "$path" ]]; then
        cp -v "$path" "${bd}/$file"
    fi
    echo "Downloading $file"
    githubLoad "${rootpath}/$file" "$path"
done

echo "Installing molokai theme for vim"
mkdir -p "$HOME/.vim/colors"
githubLoad "tomasr/molokai/master/colors/molokai.vim" "$HOME/.vim/colors/molokai.vim"

echo "Reloading settings"
source "$HOME/.bashrc"
