#!/bin/bash

githubLoad() {
    path="$1"
    dest="$2"
    wget -q --no-check-certificate -O "$dest" "https://raw.githubusercontent.com/$path"
}

rootpath="sharkdp/config-files/master/minimal-config"
files=".vimrc .bashrc .alias .profile"

bd="$HOME/.backup-config-files"
rm -r "${bd}"
mkdir "${bd}"

for file in $files; do
    path="$HOME/$file"
    echo "Backing up and $file"
    if [[ -e "$path" ]]; then
        cp -v "$path" "${bd}/$file"
    fi
    echo "Downloading minimal $file"
    githubLoad "${rootpath}/$file" "$path"
done

echo "Installing monokai theme for vim"
mkdir -p "$HOME/.vim/colors"
githubLoad "sickill/vim-monokai/master/colors/monokai.vim" "$HOME/.vim/colors/monokai.vim"
