#!/bin/bash

githubLoad() {
    path="$1"
    dest="$2"
    wget -q --no-check-certificate -O "$dest" "https://raw.githubusercontent.com/$path"
}

rootpath="sharkdp/config-files/master/minimal-config"
files=".vimrc .bashrc .alias .profile"

bd="$HOME/.backup-config-files"
if [[ -e "$bd" ]]; then
    echo -n "Delete old backup in '$bd' (Ctrl-C to cancel)? "
    read
    rm -r "${bd}"
fi
mkdir "${bd}"

for file in $files; do
    path="$HOME/$file"
    echo "Backing up and $file"
    if [[ -e "$path" ]]; then
        cp -v "$path" "${bd}/$file"
    fi
    echo "Downloading minimal $file"
    githubLoad "${rootpath}/$file" "$path"
done

# Install molokai theme for vim
mkdir -p ~/.vim/colors
githubLoad "tomasr/molokai/master/colors/molokai.vim" ~/.vim/colors/molokai.vim
